server:
  port: 0

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
#     use of random just for learning, in production can use pod name.
      transaction-id-prefix: "transfer-service-${random.value}-"
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:transdb
  h2:
    console:
      enabled: true
# Custom application properties
app:
  kafka:
    withdraw-money-topic: withdraw-money-topic
    deposit-money-topic: deposit-money-topic

logging:
  level:
    org.springframework.kafka.transaction.KafkaTransactionManager: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.apache.kafka.clients.producer.internals.TransactionManager: DEBUG
