server:
  port: 0
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: amount-deposit-event
      isolation-level: read_committed
      properties:
        spring.json.trusted.packages: com.appsdeveloperblog.*